OwnershipRules:
  directoryMatchingRules:
    - name: personal projects in experimental
      path: experimental/{{username}}/**/*
    - name: personal documentation
      path: docs/personal/{{username}}/**/*
    
